name: linux build in docker
on:
  workflow_dispatch:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  docker:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      # Required to push the built image to ghcr.io on non-PR runs.
      packages: write
    strategy:
      matrix:
        include:
          - name: debian
          - name: fedora
    steps:
      - uses: actions/checkout@fbc6f3992d24b796d5a048ff273f7fcc4a7b6c09 # v5
      - uses: docker/setup-buildx-action@8d2750c68a42422c14e847fe6c8ac0403b4cbd6f # v3

      - uses: docker/login-action@c94ce9fb468520275223c153574b00df6fe4bcc9 # v3
        with:
          registry: https://ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - run: echo "tagdate=$(date +%Y%m%d)" >> $GITHUB_ENV

      - uses: docker/build-push-action@10e90e3645eae34f1e60eeb005ba3a3d33f178e8 # v6
        name: docker image build
        with:
          file: Dockerfile.${{ matrix.name }}
          push: ${{ github.event_name != 'pull_request' }}
          tags: ghcr.io/openkj/openkj:${{ matrix.name }}-${{ env.tagdate }}

